### PR TITLE
Add typescript definition file

### PR DESCRIPTION
**Pull request by nicolaisueper**
Take it, if you're interested. :grin:

### CODE REVIEW

**Comment by reneviering** [comment]
Thanks @nicolaisueper 💖
Closes #11

**Comment by mischah** [comment]
I would prefer adding them to DefinitelyTyped.

See https://github.com/sindresorhus/semver-diff/pull/3

**Comment by mischah** [comment]
But I guess I'm too late :smirk:

**Comment by reneviering** [comment]
Hey, thanks for your advice. You are never too late. Makes sense adding them to definitelytyped. 👍

**Comment by nicolaisueper** [comment]
I thought it'd be nice if vanilla-ui-router comes as a strongly typed npm package so you don't have to install the type package seperately. But feel free to add them to dt!

**Comment by reneviering** [comment]
The vanilla-ui-router is written in pure ES6 JavaScript and I want to stay on the ES6 train to be as simple as possible. I personally don't feel the need of strong types inside the ES6 code base. But as discussed here https://github.com/sindresorhus/semver-diff/pull/3, I think it's a good compromise adding them to DefinitelyTyped to separate them from the ES6 code base. 

I reopend the issue #11 to add your type definitions @nicolaisueper  to DefinitelyTyped.

**Pull request merged**
